In [1]:
import os

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd 

In [3]:
import tensorflow as tf
print("done")

done


In [4]:
df = pd.read_csv(r"C:\Users\Yatharth\Desktop\desktop1\AI\toxic_comment_classification\train.csv")

#print("done")
#train_data.describe()
#train_data.head(10)
print("!!!!!!!!!!!!!!!!!!!!!")
print(df)

!!!!!!!!!!!!!!!!!!!!!
                      id                                       comment_text  \
0       0000997932d777bf  Explanation\nWhy the edits made under my usern...   
1       000103f0d9cfb60f  D'aww! He matches this background colour I'm s...   
2       000113f07ec002fd  Hey man, I'm really not trying to edit war. It...   
3       0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...   
4       0001d958c54c6e35  You, sir, are my hero. Any chance you remember...   
...                  ...                                                ...   
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

        toxic  severe_toxic  

In [5]:
from tensorflow.keras.layers import TextVectorization 
print("done")

done


In [6]:
X= df['comment_text']
y = df[df.columns[2:]].values

In [7]:
MAX_FEATURES = 200000

In [8]:
vectorizer = TextVectorization(max_tokens =MAX_FEATURES,
                              output_sequence_length=1800,
                              output_mode='int')

In [9]:
vectorizer.adapt(X.values)
print("adaptation complete")

adaptation complete


In [10]:
vectorizer('Hello')

<tf.Tensor: shape=(1800,), dtype=int64, numpy=array([288,   0,   0, ...,   0,   0,   0], dtype=int64)>

In [11]:
vectorizer('hello,')

<tf.Tensor: shape=(1800,), dtype=int64, numpy=array([288,   0,   0, ...,   0,   0,   0], dtype=int64)>

In [12]:
vectorized_text = vectorizer(X.values)
print("complete")

complete


In [13]:
vectorized_text

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  645,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2489, ...,     0,     0,     0],
       [  425,   441,    70, ...,     0,     0,     0],
       ...,
       [32445,  7392,   383, ...,     0,     0,     0],
       [    5,    12,   534, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]], dtype=int64)>

In [14]:
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text,y))
dataset = dataset.cache()
dataset = dataset.shuffle(16000)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8) 
#an imp feature of prefetch is that it prevents bottlenecks 
print("done")

done


In [15]:
dataset.as_numpy_iterator().next()

(array([[  115,   126,   288, ...,     0,     0,     0],
        [45471,     5,   198, ...,     0,     0,     0],
        [ 4538,    13,  5357, ...,     0,     0,     0],
        ...,
        [  997,     8,    79, ...,     0,     0,     0],
        [   67,  1683,    80, ...,     0,     0,     0],
        [   48,   679,    10, ...,     0,     0,     0]], dtype=int64),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]], dtype=int64))

In [16]:
batch_X, batch_y = dataset.as_numpy_iterator().next()

In [17]:
print(batch_X.shape)
print(batch_y.shape)

(16, 1800)
(16, 6)


In [18]:
train = dataset.take(int(len(dataset)*0.7))
val = dataset.skip(int(len(dataset)*0.7)).take(int(len(dataset)*0.2))
test = dataset.skip(int(len(dataset)*0.9)).take(int(len(dataset)*0.1))
#here we are using the skip function in order to ensure the dataset isnt taking redundant values 
print("done")

done


In [19]:
train_generator = train.as_numpy_iterator()

In [20]:
train_generator.next()

(array([[    8,    55,    52, ...,     0,     0,     0],
        [    6,   241,    43, ...,     0,     0,     0],
        [   49,    50,  2140, ...,     0,     0,     0],
        ...,
        [ 3993, 13192, 10058, ...,     0,     0,     0],
        [   27,    10,   189, ...,     0,     0,     0],
        [   98,   737,    48, ...,     0,     0,     0]], dtype=int64),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]], dtype=int64))

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Bidirectional , Dense , Embedding
print("imported")

imported


In [22]:
model = Sequential()
#create the embedding layer, . embedding will be represented as max features(number of words)+1
#32 values long is an embedding

model.add(Embedding(MAX_FEATURES+1,32))
#lstm layer will have 32 different units, with the activation function being tanh (hyperbolic tan)
#bidirectional allows us to pass informatoin backwards and forwards (both directions) across our LSTM layers 
#the importance of implementing a bidirectional layer can be understood with the help of an example
'''
lets say the sentence is "i dont hate you"/
if read from right to left, the model is going to scan the word hate first and then cite the sentence 
as toxic, which it is not 
hence it is important to scan the sentence in both the directions (bidirectonally ) in order to obtain a correct estimate of its nature 
Bidirectional is used frequently in NLP

'''
model.add(Bidirectional(LSTM(32,activation ='tanh')))
model.add(Dense(128, activation= 'relu'))
model.add(Dense(256,activation='relu'))
model.add(Dense(128,activation='relu'))
#the final layer output should map to the target dataset , y in this case 
#the sigmoid activation is used here since we are expecting the output to be somewhere between 1 and 0
model.add(Dense(6,activation='sigmoid'))
print("done")

done


In [23]:
model.compile(loss= 'BinaryCrossentropy' , optimizer = 'Adam')
print("done")

done


In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 32)          6400032   
                                                                 
 bidirectional (Bidirection  (None, 64)                16640     
 al)                                                             
                                                                 
 dense (Dense)               (None, 128)               8320      
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 6)                 774       
                                                        

In [25]:
history = model.fit(train, epochs=10 , validation_data= val)

Epoch 1/10


6981/6981 [==============================] - 4754s 681ms/step - loss: 0.0628 - val_loss: 0.0487
Epoch 2/10
6981/6981 [==============================] - 4794s 687ms/step - loss: 0.0435 - val_loss: 0.0469
Epoch 3/10
6981/6981 [==============================] - 4751s 681ms/step - loss: 0.0378 - val_loss: 0.0463
Epoch 4/10
6981/6981 [==============================] - 4698s 673ms/step - loss: 0.0329 - val_loss: 0.0453
Epoch 5/10
6981/6981 [==============================] - 4555s 652ms/step - loss: 0.0287 - val_loss: 0.0458
Epoch 6/10
6981/6981 [==============================] - 3302s 473ms/step - loss: 0.0253 - val_loss: 0.0458
Epoch 7/10
6981/6981 [==============================] - 3293s 472ms/step - loss: 0.0220 - val_loss: 0.0452
Epoch 8/10
6981/6981 [==============================] - 3267s 468ms/step - loss: 0.0194 - val_loss: 0.0482
Epoch 9/10
6981/6981 [==============================] - 4375s 627ms/step - loss: 0.0167 - val_loss: 0.0484
Epoch 10/10
6981/6981 [=========================

In [26]:
input_text = vectorizer('You freaking suck')
res = model.predict(np.array([input_text]))
#same thing as 
#res = model.predict(np.expand_dims(input_text,0))
#we cannot simply pass model.predict(input text) because the model is expecting the input ot be in the shape of (none)*(no. of values in out sequence )* (lenght of embedding)
print(res)

1/1 [==============================] - 1s 623ms/step
[[0.99964494 0.3984651  0.98037803 0.01554752 0.8967195  0.0669872 ]]


In [27]:
batch_X, batch_y = test.as_numpy_iterator().next()

In [28]:
print(batch_y)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 1 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [29]:
(model.predict(batch_X)>0.49).astype(int)

1/1 [==============================] - 0s 90ms/step


array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [30]:
res = (model.predict(batch_X)>0.49).astype(int)
print(res)

1/1 [==============================] - 0s 70ms/step
[[0 0 0 0 0 0]
 [1 0 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 1 1 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [31]:
res = res.flatten()
print(res)

[0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [32]:
from tensorflow.keras.metrics import Precision, Recall , CategoricalAccuracy
print("done")

done


In [33]:
pre = Precision()
re = Recall()
acc = CategoricalAccuracy()
print("done")

done


In [34]:
for batch in test.as_numpy_iterator():
    #unpacking the batch
    X_true, y_true = batch
    #Make a prediction
    yhat = model.predict(X_true)
    ##explore why we flattened these
    #flatten converts the dataframe into just 1 big array 
    y_true = y_true.flatten()
    yhat = yhat.flatten()
    pre.update_state(y_true, yhat)
    re.update_state(y_true, yhat)
    acc.update_state(y_true, yhat)
print("done")

1/1 [==============================] - 0s 77ms/step
done


In [35]:
print(f'Precision: {pre.result().numpy()}, Recall:{re.result().numpy()}, Accuracy:{acc.result().numpy()}')

Precision: 0.7086591124534607, Recall:0.7161252498626709, Accuracy:0.3771314024925232


In [36]:
!pip install gradio jinja2

In [37]:
!pip install ipywidgets

In [38]:
import gradio as gr
print("done")

done


In [39]:
model.save('toxicity.h5')
print('done')

done


c:\python11\Lib\site-packages\keras\src\engine\training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [40]:
def score_comment(comment):
    vectorized_comment = vectorizer([comment])
    results = model.predict(vectorized_comment)
    text = ''
    for idx, col in enumerate(df.columns[2:]):
        text+= '{}: {}\n'.format(col , results[0][idx]>0.5)
    return text

In [41]:
interface = gr.Interface(fn=score_comment, inputs='text',outputs = 'text')

In [42]:
interface.launch(share=True)

Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://107db601c117a3e633.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


1/1 [==============================] - 0s 53ms/step
